import { IsOptional, IsNumber, IsString, IsBoolean, IsArray, IsObject } from 'class-validator';

export class CreateKitchenQuoteDto {
    @IsString() @IsOptional() type?: string;
    @IsNumber() @IsOptional() kitchenSquareFootage?: number | null;
    @IsNumber() @IsOptional() kitchenLength?: number | null;
    @IsNumber() @IsOptional() kitchenWidth?: number | null;
    @IsNumber() @IsOptional() cellingHeight?: number;
    @IsNumber() @IsOptional() wallCabinetHeight?: number;
    @IsNumber() @IsOptional() stackers?: number;
    @IsBoolean() @IsOptional() isCabinetsToCelling?: boolean;
    @IsNumber() @IsOptional() price?: number;
    @IsString() @IsOptional() locationKitchen?: string;
    @IsBoolean() @IsOptional() skyScraper?: boolean;
    @IsString() @IsOptional() subFloor?: string;
    @IsBoolean() @IsOptional() crawspace?: boolean;
    @IsString() @IsOptional() demolition?: string;
    @IsBoolean() @IsOptional() dumpsterOnSite?: boolean;
    @IsNumber() @IsOptional() removeNonLoadWall?: number | null;
    @IsNumber() @IsOptional() removeLVLWall?: number | null;
    @IsNumber() @IsOptional() removeMetalWall?: number | null;
    @IsNumber() @IsOptional() recessedBeam?: number | null;
    @IsBoolean() @IsOptional() supportBasement?: boolean | null;
    @IsBoolean() @IsOptional() supportSlab?: boolean | null;
    @IsBoolean() @IsOptional() engineeringReport?: boolean | null;
    @IsString() @IsOptional() beamWrapCedar?: string;
    @IsBoolean() @IsOptional() demoElectricWiring?: boolean | null;
    @IsNumber() @IsOptional() buildNewWall?: number | null;
    @IsNumber() @IsOptional() relocateWall?: number | null;
    @IsNumber() @IsOptional() plugMold?: number | null;
    @IsNumber() @IsOptional() ledLighting?: number | null;
    @IsNumber() @IsOptional() puckLights?: number | null;
    @IsBoolean() @IsOptional() canLightFour?: boolean;
    @IsBoolean() @IsOptional() canLightSix?: boolean;
    @IsString() @IsOptional() pendantLights?: string;
    @IsString() @IsOptional() relocateRange220?: string;
    @IsString() @IsOptional() relocateRange120?: string;
    @IsString() @IsOptional() relocateCooktop220?: string;
    @IsString() @IsOptional() relocateCooktop120?: string;
    @IsString() @IsOptional() relocateDoubleOven220?: string;
    @IsString() @IsOptional() relocateFridge120?: string;
    @IsString() @IsOptional() relocateDishwasher120?: string;
    @IsString() @IsOptional() relocateHoodInsert120?: string;
    @IsString() @IsOptional() relocateMicrowave120?: string;
    @IsString() @IsOptional() relocateIsland120?: string;
    @IsString() @IsOptional() runPowerRange220?: string;
    @IsString() @IsOptional() runPowerRange120?: string;
    @IsString() @IsOptional() runPowerCooktop220?: string;
    @IsString() @IsOptional() runPowerCooktop120?: string;
    @IsString() @IsOptional() runPowerDoubleOven220?: string;
    @IsString() @IsOptional() runPowerHoodInsert120?: string;
    @IsString() @IsOptional() runPowerMicrowave120?: string;
    @IsString() @IsOptional() runPowerIsland110?: string;
    @IsString() @IsOptional() addingOutletsExisting?: string;
    @IsString() @IsOptional() addingOutletsRunPower?: string;
    @IsString() @IsOptional() addBreaker?: string;
    @IsBoolean() @IsOptional() installAirSwitch?: boolean | null;
    @IsNumber() @IsOptional() reuseSwitch?: number | null;
    @IsNumber() @IsOptional() addNewSwitch?: number | null;
    @IsNumber() @IsOptional() addNewDimmer?: number | null;
    @IsBoolean() @IsOptional() keepSwitchOnWall?: boolean | null;
    @IsBoolean() @IsOptional() addSubpanel50?: boolean | null;
    @IsBoolean() @IsOptional() addSubpanel100?: boolean | null;
    @IsBoolean() @IsOptional() upgradePanel?: boolean | null;
    @IsBoolean() @IsOptional() upgradePanelDisconnect?: boolean | null;
    @IsBoolean() @IsOptional() relocateSwitchesOutlets?: boolean | null;
    @IsString() @IsOptional() dishwasherWiring?: string;
    @IsBoolean() @IsOptional() disposalWiring?: boolean | null;
    @IsBoolean() @IsOptional() runNewDrainSupply?: boolean | null;
    @IsString() @IsOptional() relocateSinkPlumbing?: string;
    @IsString() @IsOptional() relocateFridgeWaterLine?: string;
    @IsBoolean() @IsOptional() installNewFridgeWaterBox?: boolean | null;
    @IsBoolean() @IsOptional() relocateDishwasher?: boolean | null;
    @IsString() @IsOptional() installNewWaterLineDishwasher?: string;
    @IsString() @IsOptional() runNewGasLine?: string;
    @IsString() @IsOptional() relocateGasLine?: string;
    @IsBoolean() @IsOptional() reworkSinkPlumbing?: boolean | null;
    @IsBoolean() @IsOptional() runWaterlinePotFiller?: boolean | null;
    @IsBoolean() @IsOptional() installFaucet?: boolean | null;
    @IsBoolean() @IsOptional() concreteCutPatch?: boolean | null;
    @IsString() @IsOptional() concreteCutPatchQuantity?: string;
    @IsBoolean() @IsOptional() installNewInsulationR13?: boolean | null;
    @IsString() @IsOptional() installNewInsulationR13Quantity?: string;
    @IsNumber() @IsOptional() newWindowDoubleHung?: number | null;
    @IsNumber() @IsOptional() newWindowPictureWindow?: number | null;
    @IsNumber() @IsOptional() newWindowCasement?: number | null;
    @IsBoolean() @IsOptional() windowRemoval?: boolean | null;
    @IsBoolean() @IsOptional() relocateWindow?: boolean | null;
    @IsNumber() @IsOptional() basic36UpperCabinets?: number | null;
    @IsNumber() @IsOptional() basic42UpperCabinets?: number | null;
    @IsNumber() @IsOptional() basicBaseCabinet?: number | null;
    @IsNumber() @IsOptional() basicTallCabinets?: number | null;
    @IsString() @IsOptional() basicTrimWork?: string;
    @IsString() @IsOptional() basicInstallation?: string;
    @IsNumber() @IsOptional() premium30UpperCabinet?: number | null;
    @IsNumber() @IsOptional() premium36UpperCabinets?: number | null;
    @IsNumber() @IsOptional() premium42UpperCabinets?: number | null;
    @IsNumber() @IsOptional() premiumBaseCabinet?: number | null;
    @IsNumber() @IsOptional() premiumTallCabinets?: number | null;
    @IsString() @IsOptional() premiumTrimWork?: string;
    @IsString() @IsOptional() premiumInstallation?: string;
    @IsNumber() @IsOptional() luxury30UpperCabinet?: number | null;
    @IsNumber() @IsOptional() luxury36UpperCabinets?: number | null;
    @IsNumber() @IsOptional() luxury42UpperCabinets?: number | null;
    @IsNumber() @IsOptional() luxuryBaseCabinet?: number | null;
    @IsNumber() @IsOptional() luxuryTallCabinets?: number | null;
    @IsString() @IsOptional() luxuryTrimWork?: string;
    @IsString() @IsOptional() luxuryInstallation?: string;
    @IsNumber() @IsOptional() stackersWithGlass12?: number | null;
    @IsNumber() @IsOptional() stackersWithGlass15?: number | null;
    @IsNumber() @IsOptional() stackersWithGlass18?: number | null;
    @IsNumber() @IsOptional() stackersWithoutGlass12?: number | null;
    @IsNumber() @IsOptional() stackersWithoutGlass15?: number | null;
    @IsNumber() @IsOptional() stackersWithoutGlass18?: number | null;
    @IsNumber() @IsOptional() widePocketDoors?: number | null;
    @IsString() @IsOptional() glassDoors?: string;
    @IsNumber() @IsOptional() hardwareInstallationSmall?: number | null;
    @IsNumber() @IsOptional() hardwareInstallationMedium?: number | null;
    @IsNumber() @IsOptional() hardwareInstallationLarge?: number | null;
    @IsString() @IsOptional() paintingCabinetsPaintColor?: string;
    @IsString() @IsOptional() paintingCabinetsStainColor?: string;
    @IsBoolean() @IsOptional() hardwareInstallationExistingHoles?: boolean | null;
    @IsBoolean() @IsOptional() hardwareInstallationPuttyDrill?: boolean | null;
    @IsString() @IsOptional() glassShelvesHalf?: string;
    @IsString() @IsOptional() floatingShelvesMatch?: string;
    @IsString() @IsOptional() floatingShelvesCustom?: string;
    @IsBoolean() @IsOptional() woodHoodVent30?: boolean;
    @IsBoolean() @IsOptional() woodHoodVent36?: boolean;
    @IsBoolean() @IsOptional() woodHoodVent48?: boolean;
    @IsBoolean() @IsOptional() woodHoodVent60?: boolean;
    @IsBoolean() @IsOptional() plasterSmoothCeilings?: boolean;
    @IsBoolean() @IsOptional() plasterPopcorn?: boolean;
    @IsBoolean() @IsOptional() plasterStomped?: boolean;
    @IsBoolean() @IsOptional() plasterOrangePeel?: boolean;
    @IsNumber() @IsOptional() plaster?: number | null;
    @IsBoolean() @IsOptional() ventilationHoodExteriorWall?: boolean;
    @IsBoolean() @IsOptional() ventilationHoodAtticRoof?: boolean;
    @IsBoolean() @IsOptional() ventilationHoodGarage?: boolean;
    @IsBoolean() @IsOptional() ventilationHoodRecirculating?: boolean;
    @IsBoolean() @IsOptional() countertopsQuartzBasic?: boolean;
    @IsBoolean() @IsOptional() countertopsQuartzPremium?: boolean;
    @IsBoolean() @IsOptional() countertopsQuartzLuxury?: boolean;
    @IsBoolean() @IsOptional() countertopsQuartziteBasic?: boolean;
    @IsBoolean() @IsOptional() countertopsQuartzitePremium?: boolean;
    @IsBoolean() @IsOptional() countertopsQuartziteLuxury?: boolean;
    @IsBoolean() @IsOptional() countertopsGraniteBasic?: boolean;
    @IsBoolean() @IsOptional() countertopsGranitePremium?: boolean;
    @IsBoolean() @IsOptional() countertopsGraniteLuxury?: boolean;
    @IsBoolean() @IsOptional() countertopsMarbleBasic?: boolean;
    @IsBoolean() @IsOptional() countertopsMarblePremium?: boolean;
    @IsBoolean() @IsOptional() countertopsMarbleLuxury?: boolean;
    @IsString() @IsOptional() countertopsOther?: string;
    @IsBoolean() @IsOptional() countertopTemplateFeeSmall?: boolean;
    @IsBoolean() @IsOptional() countertopTemplateFeeMedium?: boolean;
    @IsBoolean() @IsOptional() countertopTemplateFeeLarge?: boolean;
    @IsBoolean() @IsOptional() edgingEasedPolished?: boolean;
    @IsString() @IsOptional() edgingEasedPolishedQuantity?: string;
    @IsBoolean() @IsOptional() edgingBevel?: boolean;
    @IsString() @IsOptional() edgingBevelQuantity?: string;
    @IsBoolean() @IsOptional() edgingBullnose?: boolean;
    @IsString() @IsOptional() edgingBullnoseQuantity?: string;
    @IsBoolean() @IsOptional() edgingHalfBullnose?: boolean;
    @IsString() @IsOptional() edgingHalfBullnoseQuantity?: string;
    @IsBoolean() @IsOptional() edgingOgee?: boolean;
    @IsString() @IsOptional() edgingOgeeQuantity?: string;
    @IsBoolean() @IsOptional() edgingMiteredEdge?: boolean;
    @IsString() @IsOptional() edgingMiteredEdgeQuantity?: string;
    @IsNumber() @IsOptional() cutoutsSinkFaucet?: number | null;
    @IsBoolean() @IsOptional() cutoutsCooktop?: boolean | null;
    @IsString() @IsOptional() cutoutsAdditional?: string;
    @IsBoolean() @IsOptional() sinkStainlessSteelUndermount?: boolean;
    @IsBoolean() @IsOptional() sinkBlancoUndermount?: boolean;
    @IsBoolean() @IsOptional() sinkFarmhouseFireclay?: boolean;
    @IsBoolean() @IsOptional() sinkFarmhouseStainlessSteel?: boolean;
    @IsBoolean() @IsOptional() sinkFarmhouseBlanco?: boolean;
    @IsBoolean() @IsOptional() sinkCastIronUndermount?: boolean;
    @IsBoolean() @IsOptional() sinkBuildStructure?: boolean;
    @IsBoolean() @IsOptional() backsplashPrep?: boolean | null;
    @IsBoolean() @IsOptional() backsplashTile?: boolean;
    @IsString() @IsOptional() backsplashTileQuantity?: string;
    @IsBoolean() @IsOptional() backsplashQuartz?: boolean;
    @IsString() @IsOptional() backsplashQuartzQuantity?: string;
    @IsBoolean() @IsOptional() backsplashQuartzite?: boolean;
    @IsString() @IsOptional() backsplashQuartziteQuantity?: string;
    @IsBoolean() @IsOptional() backsplashGranite?: boolean;
    @IsString() @IsOptional() backsplashGraniteQuantity?: string;
    @IsBoolean() @IsOptional() backsplashMarble?: boolean;
    @IsString() @IsOptional() backsplashMarbleQuantity?: string;
    @IsString() @IsOptional() backsplashOther?: string;
    @IsBoolean() @IsOptional() stoneBacksplashTemplateFeeSmall?: boolean;
    @IsBoolean() @IsOptional() stoneBacksplashTemplateFeeMedium?: boolean;
    @IsBoolean() @IsOptional() stoneBacksplashTemplateFeeLarge?: boolean;
    @IsBoolean() @IsOptional() drywallSmoothCeilingsPopcorn?: boolean | null;
    @IsString() @IsOptional() drywallSmoothCeilingsPopcornQuantity?: string;
    @IsBoolean() @IsOptional() drywallSmoothCeilingsStomped?: boolean | null;
    @IsString() @IsOptional() drywallSmoothCeilingsStompedQuantity?: string;
    @IsBoolean() @IsOptional() drywallSmoothCeilingsOrangePeel?: boolean | null;
    @IsString() @IsOptional() drywallSmoothCeilingsOrangePeelQuantity?: string;
    @IsBoolean() @IsOptional() drywallRemoveWallpaper?: boolean | null;
    @IsBoolean() @IsOptional() drywallRepairsCeilingWalls?: boolean | null;
    @IsString() @IsOptional() applianceFreestandingRange?: string;
    @IsBoolean() @IsOptional() applianceCooktop?: boolean | null;
    @IsBoolean() @IsOptional() applianceDoubleOven?: boolean | null;
    @IsBoolean() @IsOptional() applianceHoodInsert?: boolean | null;
    @IsString() @IsOptional() applianceMicrowave?: string;
    @IsString() @IsOptional() applianceFridge?: string;
    @IsBoolean() @IsOptional() applianceBeverageFridge?: boolean | null;
    @IsString() @IsOptional() applianceIceMaker?: string;
    @IsBoolean() @IsOptional() applianceWashDryer?: boolean | null;
    @IsBoolean() @IsOptional() applianceDishwasher?: boolean | null;
    @IsBoolean() @IsOptional() applianceDisposal?: boolean | null;
    @IsString() @IsOptional() trimQuarterRound?: string;
    @IsString() @IsOptional() trimBaseboards?: string;
    @IsString() @IsOptional() trimBaseboardsQuantity?: string;
    @IsString() @IsOptional() trimCrown?: string;
    @IsString() @IsOptional() trimCrownQuantity?: string;
    @IsString() @IsOptional() trimDoorCasing?: string;
    @IsString() @IsOptional() trimDoorCasingQuantity?: string;
    @IsBoolean() @IsOptional() paintCeiling?: boolean | null;
    @IsString() @IsOptional() paintCeilingQuantity?: string;
    @IsBoolean() @IsOptional() paintWalls?: boolean | null;
    @IsString() @IsOptional() paintWallsQuantity?: string;
    @IsBoolean() @IsOptional() paintTrim?: boolean | null;
    @IsString() @IsOptional() paintTrimQuantity?: string;
    @IsBoolean() @IsOptional() paintDoor?: boolean | null;
    @IsString() @IsOptional() paintDoorQuantity?: string;
    @IsBoolean() @IsOptional() paintWindow?: boolean | null;
    @IsString() @IsOptional() paintWindowQuantity?: string;
    @IsBoolean() @IsOptional() paintExteriorDoor?: boolean;
    @IsString() @IsOptional() paintExteriorDoorQuantity?: string;
    @IsBoolean() @IsOptional() paintExteriorDoorStainSeal?: boolean;
    @IsString() @IsOptional() paintExteriorDoorStainSealQuantity?: string;
    @IsString() @IsOptional() timeFrame?: string;
    @IsString() @IsOptional() customerBudget?: string;
    @IsNumber() @IsOptional() roughQuote?: number | null;
    @IsArray() @IsOptional() projectPhotos?: any[];
    @IsArray() @IsOptional() projectDrawings?: any[];
    @IsArray() @IsOptional() projectContracts?: any[];
    @IsArray() @IsOptional() projectInvoices?: any[];
    @IsArray() @IsOptional() projectOtherDocuments?: any[];
}